---
apiVersion: v1
kind: Service
metadata:
  name: springboot-stakater-backend-rest-api
  labels:
    app: springboot-stakater-backend-rest-api
spec:
  type: NodePort
  selector:
    app: springboot-stakater-backend-rest-api
  ports:
  - protocol: TCP
    port: 8090
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-stakater-backend-rest-api
spec:
  selector:
    matchLabels:
      app: springboot-stakater-backend-rest-api
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-stakater-backend-rest-api
    spec:
      containers:
      - name: springboot-stakater-backend-rest-api
        image: zubair36/springboot-stakater-backend-rest-api:latest
        env:
        - name: Zubair_Khan
          value: "Hello from the environment"
        - name: Zubair_Khan
        value: "Zubair_Khan"
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          timeoutSeconds: 1
